version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "${MSSQL_PORT}:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  webapi:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=YourDatabaseName;User=${SA_USER};Password=${SA_PASSWORD};"

volumes:
  sqlserverdata:
